<?php

namespace Boolfalse\Larapage;

use Illuminate\Support\ServiceProvider;

class PaginationServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->loadRoutesFrom(__DIR__ . '/routes/web.php');
        $this->loadViewsFrom(__DIR__ . '/views', 'larapage');
        $this->loadMigrationsFrom(__DIR__ . '/database/migrations');
        $this->mergeConfigFrom(__DIR__ . '/config/larapage.php', 'larapage');

        // php artisan vendor:publish
        $this->publishes([
            __DIR__ . '/config/larapage.php' => config_path('larapage.php'),
        ]);
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
